import { Article } from '../types';
import { ARTICLES_DATA } from '../data/mockData';

export const WP_CONFIG = {
  domain: 'https://smartgarden.gr',
  postsEndpoint: 'https://smartgarden.gr/wp-json/wp/v2/posts?_embed=1&per_page=10',
};

export async function fetchWordPressPosts(): Promise<Article[]> {
  // 1. Try local latest_articles.json generated by cron-publish.php
  try {
    const localRes = await fetch('/latest_articles.json?t=' + Date.now(), {
      headers: { 'Accept': 'application/json' },
    });
    if (localRes.ok) {
      const localData = await localRes.json();
      if (Array.isArray(localData) && localData.length > 0) {
        return localData;
      }
    }
  } catch (e) {
    // Continue to WordPress REST API
  }

  // 2. Try WordPress REST API
  try {
    const res = await fetch(WP_CONFIG.postsEndpoint, {
      headers: {
        'Accept': 'application/json',
      },
    });

    if (!res.ok) {
      return ARTICLES_DATA;
    }

    const posts = await res.json();
    if (!Array.isArray(posts) || posts.length === 0) {
      return ARTICLES_DATA;
    }

    // Map WordPress posts to our typed Article interface
    const mapped: Article[] = posts.map((p: any, idx: number) => {
      const media = p._embedded?.['wp:featuredmedia']?.[0]?.source_url || 
                    ARTICLES_DATA[idx % ARTICLES_DATA.length].image;
      const authorName = p._embedded?.author?.[0]?.name || 'SmartGarden Team';
      const cleanExcerpt = p.excerpt?.rendered?.replace(/<[^>]+>/g, '').trim() || '';
      const cleanContent = p.content?.rendered?.replace(/<[^>]+>/g, '\n').trim() || '';
      const cleanTitle = p.title?.rendered?.replace(/&#8211;/g, '-').replace(/&#8217;/g, "'").replace(/&amp;/g, '&') || '';

      return {
        id: String(p.id),
        slug: p.slug || `post-${p.id}`,
        title: {
          el: cleanTitle,
          en: cleanTitle,
        },
        category: 'balcony',
        categoryLabel: {
          el: 'Άρθρο WordPress',
          en: 'WordPress Article',
        },
        readTime: '4 min',
        difficulty: 'easy',
        difficultyLabel: { el: 'Εύκολο', en: 'Easy' },
        date: new Date(p.date).toLocaleDateString('el-GR', { day: 'numeric', month: 'long', year: 'numeric' }),
        author: {
          name: authorName,
          role: { el: 'Συντάκτης SmartGarden', en: 'SmartGarden Editor' },
          avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
        },
        image: media,
        summary: {
          el: cleanExcerpt || 'Οδηγός για το μπαλκόνι και τον κήπο από το SmartGarden.gr',
          en: cleanExcerpt || 'Balcony and garden guide from SmartGarden.gr',
        },
        content: {
          el: cleanContent || cleanExcerpt,
          en: cleanContent || cleanExcerpt,
        },
        keyTakeaways: {
          el: ['Καθημερινή φροντίδα και σωστό πότισμα', 'Προστασία από τον καύσωνα'],
          en: ['Daily care and irrigation', 'Heatwave protection'],
        },
        socialScriptReady: true,
        socialScriptPreview: {
          hook: `Δες πώς να φροντίσεις τα φυτά σου: ${cleanTitle}`,
          caption: cleanExcerpt,
          hashtags: ['#SmartGardenGR', '#Gardening', '#GreekPlants', '#Balcony'],
        },
        likes: 24 + idx * 5,
        featured: idx === 0,
      };
    });

    return mapped.length > 0 ? mapped : ARTICLES_DATA;
  } catch (err) {
    // If CORS or offline, seamlessly fallback to rich curated articles
    return ARTICLES_DATA;
  }
}
