/**
 * Strip the article bodies out of the seed list.
 *
 * `master50Articles.ts` is 585KB of source — fifty complete articles, bodies and all —
 * and App.tsx used it as the value of `useState` before the real list arrives from
 * /latest_articles.json a few hundred milliseconds later. Every visitor downloaded and
 * parsed all fifty articles to look at a placeholder that was immediately thrown away.
 *
 * This writes the same fifty entries without `content`, which is the only large field.
 * Lists, cards and metadata still render from the seed; the bodies are needed only if the
 * fetch fails, and App.tsx imports the full file dynamically in that one case.
 *
 * Generated on every build so it cannot drift from its source.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { MASTER_50_ARTICLES } from '../src/data/master50Articles';

const dir = path.dirname(fileURLToPath(import.meta.url));
const out = path.join(dir, '..', 'src', 'data', 'master50Seed.ts');

// `content` is emptied rather than removed: the article view reads `content.el` directly,
// and a seed entry that is missing the key crashes the first render before the fetch lands.
const seed = MASTER_50_ARTICLES.map((a) => ({
  ...(a as Record<string, unknown>),
  content: { el: '', en: '' },
}));

const header = `// GENERATED by scripts/build-seed-articles.ts — do not edit.
// The same articles as master50Articles.ts, minus the \`content\` bodies. See that script
// for why. Edit the source file, not this one.
import { ArticleItem } from '../types';

export const MASTER_50_SEED = ${JSON.stringify(seed, null, 2)} as unknown as ArticleItem[];
`;

fs.writeFileSync(out, header, 'utf8');
const before = fs.statSync(path.join(dir, '..', 'src', 'data', 'master50Articles.ts')).size;
const after = fs.statSync(out).size;
console.log(
  `seed: ${seed.length} articles, ${(before / 1024).toFixed(0)}KB -> ${(after / 1024).toFixed(0)}KB`
);
