/**
 * Exports the curated photo catalogue from imageService.ts to public/photo-catalogue.json.
 *
 * The server-side video renderer (public/video-render.php) needs the exact same photo list
 * and keywords the browser uses, and a hand-copied second list would drift the first time
 * someone added a photo on one side only. This runs as part of `npm run deploy`, so the
 * JSON is always regenerated from the TypeScript source of truth.
 */

import fs from 'fs';
import path from 'path';
import {
  CURATED_GARDENING_PHOTOS,
  FALLBACK_BOTANICAL_PHOTOS,
  NEUTRAL_SCENE_PHOTOS,
} from '../src/services/imageService';

const out = {
  _generated: 'Auto-generated by scripts/export-photo-catalogue.ts — do not edit by hand.',
  _source: 'src/services/imageService.ts',
  curated: CURATED_GARDENING_PHOTOS.map((p) => ({
    url: p.url,
    keywords: p.keywords,
    category: p.category,
    alt: p.alt,
  })),
  neutral: NEUTRAL_SCENE_PHOTOS,
  fallback: FALLBACK_BOTANICAL_PHOTOS,
};

const target = path.join(process.cwd(), 'public', 'photo-catalogue.json');
fs.writeFileSync(target, JSON.stringify(out, null, 2), 'utf8');

console.log(
  `📸 photo-catalogue.json written: ${out.curated.length} curated, ` +
    `${out.neutral.length} neutral, ${out.fallback.length} fallback`
);
