// GENERATED by scripts/export-plants.ts — do not edit.
export const PLANT_INDEX: Array<{ slug: string; name: string; minTempC: number }> = [
  {
    "slug": "ntomata",
    "name": "Ντομάτα",
    "minTempC": 5
  },
  {
    "slug": "piperia",
    "name": "Πιπεριά",
    "minTempC": 8
  },
  {
    "slug": "melitzana",
    "name": "Μελιτζάνα",
    "minTempC": 10
  },
  {
    "slug": "aggouri",
    "name": "Αγγούρι",
    "minTempC": 10
  },
  {
    "slug": "kolokythi",
    "name": "Κολοκύθι",
    "minTempC": 10
  },
  {
    "slug": "fasolakia",
    "name": "Φασολάκια",
    "minTempC": 8
  },
  {
    "slug": "marouli",
    "name": "Μαρούλι",
    "minTempC": -6
  },
  {
    "slug": "spanaki",
    "name": "Σπανάκι",
    "minTempC": -9
  },
  {
    "slug": "roka",
    "name": "Ρόκα",
    "minTempC": -7
  },
  {
    "slug": "rapanaki",
    "name": "Ραπανάκι",
    "minTempC": -5
  },
  {
    "slug": "karoto",
    "name": "Καρότο",
    "minTempC": -6
  },
  {
    "slug": "kremmydi",
    "name": "Κρεμμύδι",
    "minTempC": -8
  },
  {
    "slug": "skordo",
    "name": "Σκόρδο",
    "minTempC": -10
  },
  {
    "slug": "lachano",
    "name": "Λάχανο",
    "minTempC": -10
  },
  {
    "slug": "brokolo",
    "name": "Μπρόκολο",
    "minTempC": -8
  },
  {
    "slug": "arakas",
    "name": "Αρακάς",
    "minTempC": -6
  },
  {
    "slug": "fraoula",
    "name": "Φράουλα",
    "minTempC": -12
  },
  {
    "slug": "patata",
    "name": "Πατάτα",
    "minTempC": 2
  },
  {
    "slug": "maintanos",
    "name": "Μαϊντανός",
    "minTempC": -10
  },
  {
    "slug": "anithos",
    "name": "Άνηθος",
    "minTempC": -5
  },
  {
    "slug": "vasilikos",
    "name": "Βασιλικός",
    "minTempC": 10
  },
  {
    "slug": "rigani",
    "name": "Ρίγανη",
    "minTempC": -15
  },
  {
    "slug": "thymari",
    "name": "Θυμάρι",
    "minTempC": -12
  },
  {
    "slug": "dendrolivano",
    "name": "Δεντρολίβανο",
    "minTempC": -10
  },
  {
    "slug": "menta",
    "name": "Μέντα / Δυόσμος",
    "minTempC": -15
  },
  {
    "slug": "levanta",
    "name": "Λεβάντα",
    "minTempC": -15
  },
  {
    "slug": "faskomilo",
    "name": "Φασκόμηλο",
    "minTempC": -12
  },
  {
    "slug": "melissochorto",
    "name": "Μελισσόχορτο",
    "minTempC": -15
  },
  {
    "slug": "dafni",
    "name": "Δάφνη",
    "minTempC": -8
  },
  {
    "slug": "chamomili",
    "name": "Χαμομήλι",
    "minTempC": -10
  },
  {
    "slug": "gerani",
    "name": "Γεράνι / Πελαργόνιο",
    "minTempC": 0
  },
  {
    "slug": "petounia",
    "name": "Πετούνια",
    "minTempC": 2
  },
  {
    "slug": "kalimprachoi",
    "name": "Καλιμπραχόη",
    "minTempC": 2
  },
  {
    "slug": "triantafyllia",
    "name": "Τριανταφυλλιά",
    "minTempC": -15
  },
  {
    "slug": "ortansia",
    "name": "Ορτανσία",
    "minTempC": -12
  },
  {
    "slug": "gardenia",
    "name": "Γαρδένια",
    "minTempC": -3
  },
  {
    "slug": "voukamvilia",
    "name": "Βουκαμβίλια",
    "minTempC": 0
  },
  {
    "slug": "giasemi",
    "name": "Γιασεμί",
    "minTempC": -7
  },
  {
    "slug": "chrysanthemo",
    "name": "Χρυσάνθεμο",
    "minTempC": -8
  },
  {
    "slug": "kyklamino",
    "name": "Κυκλάμινο",
    "minTempC": -2
  },
  {
    "slug": "alexandrino",
    "name": "Αλεξανδρινό",
    "minTempC": 10
  },
  {
    "slug": "toulipa",
    "name": "Τουλίπα",
    "minTempC": -15
  },
  {
    "slug": "narkissos",
    "name": "Νάρκισσος",
    "minTempC": -15
  },
  {
    "slug": "lemonia",
    "name": "Λεμονιά",
    "minTempC": -3
  },
  {
    "slug": "portokalia",
    "name": "Πορτοκαλιά",
    "minTempC": -4
  },
  {
    "slug": "koumkouat",
    "name": "Κουμκουάτ",
    "minTempC": -6
  },
  {
    "slug": "elia",
    "name": "Ελιά",
    "minTempC": -10
  },
  {
    "slug": "sykia",
    "name": "Συκιά",
    "minTempC": -12
  },
  {
    "slug": "rodia",
    "name": "Ροδιά",
    "minTempC": -12
  },
  {
    "slug": "pyxari",
    "name": "Πυξάρι",
    "minTempC": -18
  },
  {
    "slug": "monstera",
    "name": "Μονστέρα",
    "minTempC": 10
  },
  {
    "slug": "kaoutsoukodentro",
    "name": "Καουτσουκόδεντρο",
    "minTempC": 12
  },
  {
    "slug": "zamioulkas",
    "name": "Ζαμιοκούλκας",
    "minTempC": 12
  },
  {
    "slug": "sansevieria",
    "name": "Σανσεβιέρια",
    "minTempC": 10
  },
  {
    "slug": "pothos",
    "name": "Πόθος",
    "minTempC": 12
  },
  {
    "slug": "spathifyllo",
    "name": "Σπαθίφυλλο",
    "minTempC": 12
  },
  {
    "slug": "aloe-vera",
    "name": "Αλόη",
    "minTempC": 5
  },
  {
    "slug": "orchidea",
    "name": "Ορχιδέα Φαλαινόψις",
    "minTempC": 15
  },
  {
    "slug": "ficus-lyrata",
    "name": "Φίκος Λυράτα",
    "minTempC": 12
  }
];
